services: 
  backend: 
    build: ./backend
    #image: zawodev/clobber-online-backend:latest
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes: 
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports: 
      - "8000:8000"
    environment: 
      - FRONTEND_URL=http://${PUBLIC_IP}
    depends_on: 
      - redis

  redis: 
    image: redis:7
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API: http://${PUBLIC_IP}/api/v2
        VUE_APP_WSGLOBALCHAT: ws://${PUBLIC_IP}/ws/chat/global
        VUE_APP_WSROOMCHAT: ws://${PUBLIC_IP}/ws/chat/room
        VUE_APP_WSROOM: ws://${PUBLIC_IP}/ws/game
        VUE_APP_SSOLINK: http://${PUBLIC_IP}/accounts/google/login
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  media_volume:
  static_volume: