services:
  backend:
    build: ./backend
    #image: zawodev/clobber-online-backend:latest
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  frontend:
    image: jborsuk/clobberfront:latest
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  media_volume:
  static_volume:

