# Generated by Django 5.2.1 on 2025-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
