# Generated by Django 5.2.1 on 2025-06-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_height_room_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='creator_color',
            field=models.CharField(choices=[('black', 'black'), ('white', 'white')], default='black', max_length=5),
        ),
        migrations.AddField(
            model_name='room',
            name='vs_ai',
            field=models.BooleanField(default=False),
        ),
    ]
