# Generated by Django 5.2.1 on 2025-06-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('rooms', '0004_room_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.challenge'),
        ),
    ]
