# Generated by Django 5.2.1 on 2025-06-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameresult_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='game.game'),
        ),
    ]
